### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by chrisblossom** [liady/webpack-node-externals#1]
Thanks for putting this together. Just curious if there are any benefits over using this over what is recommended in http://jlongster.com/Backend-Apps-with-Webpack--Part-I

``` javascript
var webpack = require('webpack');
var path = require('path');
var fs = require('fs');

var nodeModules = {};
fs.readdirSync('node_modules')
  .filter(function(x) {
    return ['.bin'].indexOf(x) === -1;
  })
  .forEach(function(mod) {
    nodeModules[mod] = 'commonjs ' + mod;
  });

module.exports = {
  entry: './src/main.js',
  target: 'node',
  output: {
    path: path.join(__dirname, 'build'),
    filename: 'backend.js'
  },
  externals: nodeModules
}

```

**Comment by liady** [comment]
Hey, 
Thanks for the feedback. 
As you can see, this blog post is referenced as my inspiration.

I built this mini library in order to encapsulate this code, and allow easy reusing across different projects. 

It is also configurable, backed in tests, and even allows defining a "whitelist" of paths that *should* be bundled.

**Comment by chrisblossom** [comment]
Thanks for the response! I am using this with a new project and will let you know if I run into any issues.

**Comment by chrisblossom** [comment]
@liady just FYI, I think your module fixes the issue described here: https://github.com/RickWong/react-isomorphic-starterkit/pull/104

**Comment by liady** [comment]
Thanks! I submitted a PR there.
