### ISSUE TITLE
Question | Why is not bundling node_modules good? 

### ISSUE THREAD

**Issue by omerts** [liady/webpack-node-externals#13]
Hey,

I am trying to understand why not to bundle node_modules in our server bundle. I also read: http://jlongster.com/Backend-Apps-with-Webpack--Part-I, which from issue #1 seems to be the inspiration for this plugin, but there isn't a real explanation why not to bundle node_modules. In the above post, and in this plugin, you just state that it is not good, but why?

On the other hand, imho, bundling node_modules, makes deployment much smoother. For one, instead of having to copy the whole node_modules folder, you just copy the bundle, which is in our case is about 1Mb vs node_modules being 300+ Mbs. Secondly, when building into a `dist` folder (so we can have a single deployment point), trying to automatically copy node_modules into that folder, results in `too many open files` error.

Also (this is kind of a guess), correct me if I am wrong, but wouldn't having to load a "big" bundle file, would be like a one time thing while starting the server, and will only affect the initial load time of the server, which isn't that important any way?

**Comment by wmertens** [comment]
The real reason is that binary modules simply cannot be bundled into a js bundle…

**Comment by omerts** [comment]
I see what you are saying, but I think most packages don't have any binaries. We run into a case with a package that has binaries, only once so far (I know that there are many many other packages we didn't try it, but we did try many). It was a package for running node.js as a service on windows. So for that specific case, we used copy-webpack-plugin, and just copied the binaries to the output directory.

**Comment by omerts** [comment]
Just to add, for development, I totally think this is good, since when you are watching your files and automatically bundling, keeping node_modules externally saves a lot of the bundle time .

**Comment by liady** [comment]
@omerts When writing a node library, for instance, you may want to split your code to several files, and use Webpack to bundle them. However - you wouldn't want to bundle your code with its entire node_modules dependencies, for two reasons:
1. That will bloat your library on npm
2, and most important - it goes against the entire npm dependencies management. If you're using Lodash, and the consumer of your library also has the same Lodash dependency, npm makes sure that it will be added only once. But bundling Lodash in your library will actually make it included twice, since npm is no longer managing this dependency.

As a consumer of a library, I want the library code to include only its logic, and just state its dependencies so they could me merged/resolved with the rest of the dependencies in my project. Bundling your code with your dependencies makes it virtually impossible.

**Comment by omerts** [comment]
@liady Got it, thanks a lot.
