### ISSUE TITLE
Doesn't work with yarn workspaces by default

### ISSUE THREAD

**Issue by bryzaguy** [liady/webpack-node-externals#39]
I have a monorepo which is essentially a repository with many npm packages in it and I just started using yarn workspaces which hoists all dependencies to the root of the repository.  I realized that all my node_modules were getting included because they were now located in a node_modules folder two parents up.  So I had to switch to `externals: /node_modules/`

**Comment by alexrqs** [comment]
I'm having the same issue so that PR witth moduleDirs will be awesome, I just don't know how @barraq resolved the issue with 2 node folders because when you are using lerna, the folders inside `packages/` will have their own `node_modules` with the symlinks created by lerna and other node packages will be on the root, that makes 2 node_modules folder to inspect. 
This is valid with workspaces only, if you dont use workspaces all is good but for my particular case where I'm using a monorepo full of react components and on the root folder a storybook installation to preview the components, if I dont use workspaces react gets repeated and doesn't work so thats why the approach with webpack-node-externals is important.

**Comment by barraq** [comment]
@alexrqs actually I am using this patch for our monorepo at Freeletics. I simply have this configuration:

```
externals: [nodeExternals({
  modulesDirs: ['node_modules', path.resolve(__dirname, '../../node_modules')],
})],
```
and it works  like a charm ;) actually that was the reason of the patch.

**Comment by chadly** [comment]
@barraq you can accomplish the same thing without any code changes to this package by just including multiple instances:

```js
externals: [
  nodeExternals(),
  nodeExternals({
    modulesDir: path.resolve(__dirname, '../../node_modules')
})],
```

**Comment by atdixon** [comment]
+1

Ideally the default modulesDir behavior would be to walk the workspace to its root (consulting all node_modules directories from package to root); thus, webpack-node-externals would work out of the box for monorepos.

The current solution of hard-coding module dirs is brittle (ie, breaks if a package is moved/copied etc within the monorepo).

Also, node itself seems to resolve from node_modules up the directory tree. Webpack and other libraries, similarly. So this would be idiomatic, no? If so, perhaps there's a direct/normalized library/facility for doing this walk that could be leveraged.

**Comment by sibelius** [comment]
how can I whitelist `webpack/hot/poll?1000` in a monorepo setup?

**Comment by shaunlmason** [comment]
> how can I whitelist `webpack/hot/poll?1000` in a monorepo setup?

Try:

```
 externals: [
     nodeExternals({
         modulesDir: path.resolve(__dirname, './node_modules'),
         whitelist: ['webpack/hot/poll?1000']
     }),
     nodeExternals({
         modulesDir: path.resolve(__dirname, '../../node_modules'),
         whitelist: ['webpack/hot/poll?1000']
     })
 ],
```

**Comment by moshest** [comment]
If you have many packages and you want to query them all, use this:

```ts
import glob from 'glob';

const externals = glob
    .sync('*/node_modules/', { absolute: true, cwd: __dirname })
    .map((modulesDir) => nodeExternals({ modulesDir })),
```

**Comment by liady** [comment]
In version 2, you can now specify `additionalModuleDirs` in the options.
