### ISSUE TITLE
"Why is not bundling node_modules a good thing" info not correct?

### ISSUE THREAD

**Issue by stevemao** [liady/webpack-node-externals#55]
> It goes against the entire npm dependencies management. If you're using Lodash, and the consumer of your library also has the same Lodash dependency, npm makes sure that it will be added only once. But bundling Lodash in your library will actually make it included twice, since npm is no longer managing this dependency.

I'm not sure if this is correct. Webpack will only bundle it once if within the same version range. I think another reason to use this module is some modules might use binary. Some might use unconventional way to load modules. Some might use `fs` with relative paths.

**Comment by dmngu9** [comment]
Hi steve. Any update?

**Comment by stevemao** [comment]
We shouldn't bundle node_modules, but the reason in README is wrong.

**Comment by liady** [comment]
Hi, if still relevant - when building a library for npm (or for Node environment), there is actually no need to bundle its dependencies. Since it will run in Node, it can just `require` its dependencies (without bundling).
The purpose of this library is to allow running Webpack on the source code - while keeping the dependencies unbundled.
